version: '3.8'

services:
  app: 
    container_name: backend-services
    build: 
      context: .
    ports:
      - "9000:9000"
    restart: always 
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: